export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const TABLES_REQUEST = 'TABLES_REQUEST'
export const TABLES_SUCCESS = 'TABLES_SUCCESS'
export const TABLES_FAILURE = 'TABLES_FAILURE'

export const MAKE_RESERVATION_REQUEST = 'MAKE_RESERVATION_REQUEST'
export const MAKE_RESERVATION_SUCCESS = 'MAKE_RESERVATION_SUCCESS'
export const MAKE_RESERVATION_FAILURE = 'MAKE_RESERVATION_FAILURE'

export const FETCH_MY_RESERVATION_REQUEST = 'FETCH_MY_RESERVATION_REQUEST'
export const FETCH_MY_RESERVATION_SUCCESS = 'FETCH_MY_RESERVATION_SUCCESS'
export const FETCH_MY_RESERVATION_FAILURE = 'FETCH_MY_RESERVATION_FAILURE'

export const INVITE_REQUEST = 'INVITE_REQUEST'
export const INVITE_SUCCESS = 'INVITE_SUCCESS'
export const INVITE_FAILURE = 'INVITE_FAILURE'

export const KICK_REQUEST = 'KICK_REQUEST'
export const KICK_SUCCESS = 'KICK_SUCCESS'
export const KICK_FAILURE = 'KICK_FAILURE'

export const CLEAR_RESERVATIONS_REQUEST = 'CLEAR_RESERVATIONS_REQUEST'
export const CLEAR_RESERVATIONS = 'CLEAR_RESERVATIONS'

export const LOGOUT = 'LOGOUT'
export const MAKE_RESERVATION = 'MAKE_RESERVATION'
export const ORDER = 'ORDER'
export const REMOVE_TIME = 'REMOVE_TIME'
