export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const TABLES_REQUEST = 'TABLES_REQUEST'
export const TABLES_SUCCESS = 'TABLES_SUCCESS'
export const TABLES_FAILURE = 'TABLES_FAILURE'

export const LOGOUT = 'LOGOUT'
export const MAKE_RESERVATION = 'MAKE_RESERVATION'
export const ORDER = 'ORDER'
