export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const HOME = '/'
export const ACCOUNT = '/account'
export const TABLES = '/tables'
export const MY_RESERVATIONS = '/my-reservations'
